# - Try to find OpenGLES
# Once done this will define
#  
#  OPENGLES_FOUND        - system has OpenGLES
#  OPENGLES_INCLUDE_DIR  - the GL include directory
#  OPENGLES_LIBRARIES    - Link these to use OpenGLES

FIND_PATH(
	OPENGLES_INCLUDE_DIR GLES/gl.h 
)

FIND_LIBRARY(
	OPENGLES_LIBRARIES NAMES  GLESv1_CM
)

IF(OPENGLES_LIBRARIES)
  SET(OPENGLES_FOUND "YES" )
ENDIF(OPENGLES_LIBRARIES)

MARK_AS_ADVANCED(
  OPENGLES_INCLUDE_DIR
  OPENGLES_LIBRARIES
)


